@echo off
setlocal EnableExtensions EnableDelayedExpansion
cd /d "%~dp0"

echo ============================================
echo  SentinelAgent Build Pipeline (Nuitka + Zig)
echo ============================================
echo.

set "BUILD_MODE=user"
set "OUTPUT_NAME=SentinelAgent.exe"
set "BUILD_STYLE=onefile"
set "SERVER_PRESET="
set "CUSTOM_SERVER_URL="
set "LAST_ERROR_MSG="
set "ICON_PATH=resources\favicon.ico"
set "ICON_FLAG="

if exist "%ICON_PATH%" (
    set "ICON_FLAG=--windows-icon-from-ico=%ICON_PATH%"
)

:parse_args
if "%~1"=="" goto args_done
if /I "%~1"=="/admin" (
    set "BUILD_MODE=admin"
    shift
    goto parse_args
)
if /I "%~1"=="/onefile" (
    set "BUILD_STYLE=onefile"
    shift
    goto parse_args
)
if /I "%~1"=="/standalone" (
    set "BUILD_STYLE=standalone"
    shift
    goto parse_args
)
if /I "%~1"=="/prod" (
    set "SERVER_PRESET=prod"
    shift
    goto parse_args
)
if /I "%~1"=="/demo" (
    set "SERVER_PRESET=demo"
    shift
    goto parse_args
)
if /I "%~1"=="/dev" (
    set "SERVER_PRESET=dev"
    shift
    goto parse_args
)
if /I "%~1"=="/server" (
    if "%~2"=="" (
        echo [ERROR] /server requires a URL argument.
        exit /b 1
    )
    set "SERVER_PRESET=custom"
    set "CUSTOM_SERVER_URL=%~2"
    shift
    shift
    goto parse_args
)

if "%~1" NEQ "" set "OUTPUT_NAME=%~1"
shift
goto parse_args

:args_done

if /I "%BUILD_MODE%"=="admin" (
    echo [Mode] Admin build enabled (UAC prompt required at launch)
) else (
    echo [Mode] User build (no forced UAC prompt)
)
if /I "%BUILD_STYLE%"=="onefile" (
    echo [Profile] Onefile - single EXE deliverable
) else (
    echo [Profile] Standalone - folder output with tk-inter plugin
)
echo.

if not defined SERVER_PRESET (
    echo Select target server for this EXE:
    echo   [1] Production  - https://zerowatch.deepcytes.io
    echo   [2] Demo/Test   - https://dccveengine-vm.eastus.cloudapp.azure.com
    echo   [3] Development - http://localhost:3001
    echo.
    choice /c 123 /n /m "Enter choice (1/2/3): "
    if errorlevel 3 (
        set "SERVER_PRESET=dev"
    ) else if errorlevel 2 (
        set "SERVER_PRESET=demo"
    ) else if errorlevel 1 (
        set "SERVER_PRESET=prod"
    )

    if not defined SERVER_PRESET (
        echo [ERROR] Failed to read server choice.
        echo [HINT] Use a preset flag like /prod, /demo, or /dev.
        exit /b 1
    )
)
echo [DEBUG] SERVER_PRESET resolved to: %SERVER_PRESET%

if /I "%SERVER_PRESET%"=="prod" set "RAW_SERVER_URL=https://zerowatch.deepcytes.io"
if /I "%SERVER_PRESET%"=="demo" set "RAW_SERVER_URL=https://dccveengine-vm.eastus.cloudapp.azure.com"
if /I "%SERVER_PRESET%"=="dev" set "RAW_SERVER_URL=http://localhost:3001"
if /I "%SERVER_PRESET%"=="custom" set "RAW_SERVER_URL=%CUSTOM_SERVER_URL%"

if not defined RAW_SERVER_URL (
    echo [ERROR] Failed to resolve server URL.
    exit /b 1
)

set "BASE_API_URL=%RAW_SERVER_URL%"
if /I not "%BASE_API_URL:~-4%"=="/api" set "BASE_API_URL=%BASE_API_URL%/api"

echo [Server] EXE will be pinned to: %BASE_API_URL%
echo.

echo [1/5] Installing build dependencies...
py -3.11 -m pip install nuitka wmi requests zstandard "python-socketio[client]"
if errorlevel 1 (
    set "LAST_ERROR_MSG=Failed to install build dependencies."
    goto build_failed
)
echo.

echo [2/5] Writing build-time server config...
set "BUILD_CFG=agent_build_config.py"
> "%BUILD_CFG%" echo # Auto-generated by build_agent.bat
>> "%BUILD_CFG%" echo FORCED_BASE_API_URL = "%BASE_API_URL%"
if errorlevel 1 (
    set "LAST_ERROR_MSG=Failed to write %BUILD_CFG%."
    goto build_failed
)
echo.

echo [3/5] Preparing output directory...
if not exist "build" mkdir "build"
if exist "build\%OUTPUT_NAME%" (
    del /f /q "build\%OUTPUT_NAME%" >nul 2>nul
    if exist "build\%OUTPUT_NAME%" (
        set "LAST_ERROR_MSG=build\%OUTPUT_NAME% is in use. Close SentinelAgent and retry."
        del /q "%BUILD_CFG%" >nul 2>nul
        goto build_failed
    )
)
rem Clean corrupted build directories to prevent Nuitka crashes
if exist "build\sentinel_agent.build" rd /s /q "build\sentinel_agent.build"
if exist "build\sentinel_agent.onefile-build" rd /s /q "build\sentinel_agent.onefile-build"
echo.

echo [4/5] Compiling sentinel_agent.py
echo       This may take several minutes (Python -> C -> binary)
echo.
set "BASE_FLAGS=--assume-yes-for-downloads --zig --windows-console-mode=disable --output-dir=build --output-filename=%OUTPUT_NAME% %ICON_FLAG% --include-data-file=%ICON_PATH%=favicon.ico"

if /I "%BUILD_STYLE%"=="onefile" (
    for /f "delims=" %%i in ('py -3.11 -c "import sys; print(sys.prefix)"') do set "PYTHON_PREFIX=%%i"
    set "TCL_ROOT=!PYTHON_PREFIX!\tcl"
    if not exist "!TCL_ROOT!\tcl8.6\init.tcl" (
        echo [ERROR] Cannot find Tcl library at !TCL_ROOT!\tcl8.6
        echo [ERROR] Cannot build - Tcl/Tk not found in Python installation.
        set "LAST_ERROR_MSG=Tcl library not found."
        goto build_failed
    )
    set "STYLE_FLAGS=--onefile --onefile-no-compression --enable-plugin=tk-inter --onefile-tempdir-spec={CACHE_DIR}/ZeroWatch/extracted"
) else (
    set "STYLE_FLAGS=--standalone --enable-plugin=tk-inter"
)

call :run_compile
set "BUILD_EXIT=%ERRORLEVEL%"
if not "%BUILD_EXIT%"=="0" (
    echo [WARN] Zig build failed with exit code %BUILD_EXIT%. Retrying without --zig...
    set "BASE_FLAGS=--assume-yes-for-downloads --windows-console-mode=disable --output-dir=build --output-filename=%OUTPUT_NAME% %ICON_FLAG% --include-data-file=%ICON_PATH%=favicon.ico"
    call :run_compile
    set "BUILD_EXIT=%ERRORLEVEL%"
)

del /q "%BUILD_CFG%" >nul 2>nul
if not "%BUILD_EXIT%"=="0" (
    set "LAST_ERROR_MSG=Build failed after retry."
    goto build_failed
)

goto build_success

:run_compile
if /I "%BUILD_MODE%"=="admin" (
    py -3.11 -m nuitka ^
            %BASE_FLAGS% ^
            %STYLE_FLAGS% ^
            --company-name="DeepCytes" ^
            --product-name="ZeroWatch Sentinel Agent" ^
            --file-description="ZeroWatch Endpoint Security Agent" ^
            --file-version=1.1.1.0 ^
            --product-version=1.1.1.0 ^
            --windows-uac-admin ^
            sentinel_agent.py
) else (
    py -3.11 -m nuitka ^
            %BASE_FLAGS% ^
            %STYLE_FLAGS% ^
            --company-name="DeepCytes" ^
            --product-name="ZeroWatch Sentinel Agent" ^
            --file-description="ZeroWatch Endpoint Security Agent" ^
            --file-version=1.1.1.0 ^
            --product-version=1.1.1.0 ^
            sentinel_agent.py
)
exit /b %ERRORLEVEL%

:build_success

if /I "%BUILD_STYLE%"=="standalone" if not exist "build\sentinel_agent.dist\%OUTPUT_NAME%" (
    set "LAST_ERROR_MSG=Build completed without producing build\sentinel_agent.dist\%OUTPUT_NAME%."
    goto build_failed
)

if /I "%BUILD_STYLE%"=="onefile" if not exist "build\%OUTPUT_NAME%" (
    set "LAST_ERROR_MSG=Build completed without producing build\%OUTPUT_NAME%."
    goto build_failed
)

echo.
echo [5/5] Build complete!
if /I "%BUILD_STYLE%"=="onefile" (
    echo       Output: build\%OUTPUT_NAME%
) else (
    echo       Output: build\sentinel_agent.dist\%OUTPUT_NAME%
)
echo.

echo [CLEANUP] Removing build artifacts...
if exist "build\sentinel_agent.build" rd /s /q "build\sentinel_agent.build"
if exist "build\sentinel_agent.onefile-build" rd /s /q "build\sentinel_agent.onefile-build"
if /I "%BUILD_STYLE%"=="onefile" if exist "build\sentinel_agent.dist" rd /s /q "build\sentinel_agent.dist" >nul 2>nul
if exist "__pycache__" rd /s /q "__pycache__"
echo       Artifacts cleaned.
echo.
echo [NOTE] This EXE is pinned to: %BASE_API_URL%
echo [NOTE] If Microsoft Defender blocks it, sign the binary with a trusted code-signing certificate.
echo.
exit /b 0

:build_failed
if exist "%BUILD_CFG%" del /q "%BUILD_CFG%" >nul 2>nul
if not defined BUILD_EXIT set "BUILD_EXIT=1"
echo [ERROR] %LAST_ERROR_MSG%
echo [ERROR] Exit code: %BUILD_EXIT%
echo.
echo Build did not finish. Review the error messages above.
pause
exit /b %BUILD_EXIT%
