@echo off
setlocal EnableExtensions EnableDelayedExpansion
cd /d "%~dp0"

echo ============================================
echo  SentinelAgent Build Pipeline (Nuitka + Zig)
echo ============================================
echo.

set "BUILD_MODE=user"
set "OUTPUT_NAME=SentinelAgent.exe"
set "BUILD_STYLE=onefile"
set "SERVER_PRESET="
set "CUSTOM_SERVER_URL="
set "LAST_ERROR_MSG="
set "ICON_PATH=resources\favicon.ico"
set "ICON_FLAG="
set "CLEAN_BUILD=0"
set "SKIP_PIP=0"

if exist "%ICON_PATH%" (
    set "ICON_FLAG=--windows-icon-from-ico=%ICON_PATH%"
)

:parse_args
if "%~1"=="" goto args_done
if /I "%~1"=="/admin" (
    set "BUILD_MODE=admin"
    shift
    goto parse_args
)
if /I "%~1"=="/onefile" (
    set "BUILD_STYLE=onefile"
    shift
    goto parse_args
)
if /I "%~1"=="/standalone" (
    set "BUILD_STYLE=standalone"
    shift
    goto parse_args
)
if /I "%~1"=="/prod" (
    set "SERVER_PRESET=prod"
    shift
    goto parse_args
)
if /I "%~1"=="/demo" (
    set "SERVER_PRESET=demo"
    shift
    goto parse_args
)
if /I "%~1"=="/dev" (
    set "SERVER_PRESET=dev"
    shift
    goto parse_args
)
if /I "%~1"=="/clean" (
    set "CLEAN_BUILD=1"
    shift
    goto parse_args
)
if /I "%~1"=="/fast" (
    set "SKIP_PIP=1"
    shift
    goto parse_args
)
if /I "%~1"=="/nopip" (
    set "SKIP_PIP=1"
    shift
    goto parse_args
)
if /I "%~1"=="/server" (
    if "%~2"=="" (
        echo [ERROR] /server requires a URL argument.
        exit /b 1
    )
    set "SERVER_PRESET=custom"
    set "CUSTOM_SERVER_URL=%~2"
    shift
    shift
    goto parse_args
)

if "%~1" NEQ "" set "OUTPUT_NAME=%~1"
shift
goto parse_args

:args_done

if /I "%BUILD_MODE%"=="admin" (
    echo [Mode] Admin build enabled ^(UAC prompt required at launch^)
) else (
    echo [Mode] User build ^(no forced UAC prompt^)
)
if /I "%BUILD_STYLE%"=="onefile" (
    echo [Profile] Onefile - single EXE deliverable
) else (
    echo [Profile] Standalone - folder output with tk-inter plugin
)
if "%CLEAN_BUILD%"=="1" (
    echo [Cache] Clean build requested - cache will be purged
) else (
    echo [Cache] Incremental build enabled ^(fast recompilation^)
)
echo.

if not defined SERVER_PRESET (
    echo Select target server for this EXE:
    echo   [1] Production  - https://zerowatch.deepcytes.io
    echo   [2] Demo/Test   - https://zerowatch-testing.eastasia.cloudapp.azure.com
    echo   [3] Development - http://localhost:3001
    echo.
    choice /c 123 /n /m "Enter choice (1/2/3): "
    if errorlevel 3 (
        set "SERVER_PRESET=dev"
    ) else if errorlevel 2 (
        set "SERVER_PRESET=demo"
    ) else if errorlevel 1 (
        set "SERVER_PRESET=prod"
    )

    if not defined SERVER_PRESET (
        echo [ERROR] Failed to read server choice.
        echo [HINT] Use a preset flag like /prod, /demo, or /dev.
        exit /b 1
    )
)
echo [DEBUG] SERVER_PRESET resolved to: %SERVER_PRESET%

if /I "%SERVER_PRESET%"=="prod" set "RAW_SERVER_URL=https://zerowatch.deepcytes.io"
if /I "%SERVER_PRESET%"=="demo" set "RAW_SERVER_URL=https://zerowatch-testing.eastasia.cloudapp.azure.com"
if /I "%SERVER_PRESET%"=="dev" set "RAW_SERVER_URL=http://localhost:3001"
if /I "%SERVER_PRESET%"=="custom" set "RAW_SERVER_URL=%CUSTOM_SERVER_URL%"

if not defined RAW_SERVER_URL (
    echo [ERROR] Failed to resolve server URL.
    exit /b 1
)

set "BASE_API_URL=%RAW_SERVER_URL%"
if /I not "%BASE_API_URL:~-4%"=="/api" set "BASE_API_URL=%BASE_API_URL%/api"

echo [Server] EXE will be pinned to: %BASE_API_URL%
echo.

if "%SKIP_PIP%"=="1" (
    echo [1/5] Skipping dependency check ^(/fast enabled^)...
) else (
    echo [1/5] Checking build dependencies...
    py -3.11 -m pip install --disable-pip-version-check --quiet -r requirements-windows.txt
    if errorlevel 1 (
        echo [WARN] requirements-windows.txt install had issues, installing core deps directly...
        py -3.11 -m pip install --disable-pip-version-check nuitka wmi requests zstandard "python-socketio[client]" cryptography
    )
    if errorlevel 1 (
        set "LAST_ERROR_MSG=Failed to install build dependencies."
        goto build_failed
    )
)
echo.

echo [2/5] Writing build-time server config...
set "BUILD_CFG=agent_build_config.py"
> "%BUILD_CFG%" echo # Auto-generated by build_agent.bat
>> "%BUILD_CFG%" echo FORCED_BASE_API_URL = "%BASE_API_URL%"
if errorlevel 1 (
    set "LAST_ERROR_MSG=Failed to write %BUILD_CFG%."
    goto build_failed
)
echo.

echo [2.5/5] Validating certificate pinning configuration...
py -3.11 verify_pins.py %SERVER_PRESET%
if errorlevel 1 (
    echo [ERROR] Pin validation failed! Check error messages above.
    set "LAST_ERROR_MSG=Pin validation check failed."
    del /q "%BUILD_CFG%" >nul 2>nul
    goto build_failed
)
echo.

echo [3/5] Preparing output directory...
if not exist "build" mkdir "build"
if exist "build\%OUTPUT_NAME%" (
    del /f /q "build\%OUTPUT_NAME%" >nul 2>nul
    if exist "build\%OUTPUT_NAME%" (
        set "LAST_ERROR_MSG=build\%OUTPUT_NAME% is in use. Close SentinelAgent and retry."
        del /q "%BUILD_CFG%" >nul 2>nul
        goto build_failed
    )
)
if "%CLEAN_BUILD%"=="1" (
    echo [CLEAN] Purging previous build directory...
    if exist "build\sentinel_agent.build" rd /s /q "build\sentinel_agent.build"
    if exist "build\sentinel_agent.onefile-build" rd /s /q "build\sentinel_agent.onefile-build"
)
echo.

echo [4/5] Compiling sentinel_agent.py
echo       This will utilize all available CPU cores (%NUMBER_OF_PROCESSORS% threads)
echo.
set "PACKAGE_FLAGS=--include-package=common --include-package=scanner --include-package=platforms --include-package=windows --nofollow-import-to=linux --nofollow-import-to=macos"
set "DATA_FLAGS=--include-data-dir=resources=resources"
set "SPEED_FLAGS=--lto=no --jobs=%NUMBER_OF_PROCESSORS%"
set "BASE_FLAGS=--assume-yes-for-downloads --zig --windows-console-mode=disable --output-dir=build --output-filename=%OUTPUT_NAME% %ICON_FLAG% --include-data-file=%ICON_PATH%=favicon.ico %PACKAGE_FLAGS% %DATA_FLAGS% %SPEED_FLAGS%"

if /I "%BUILD_STYLE%"=="onefile" (
    for /f "delims=" %%i in ('py -3.11 -c "import sys; print(sys.prefix)"') do set "PYTHON_PREFIX=%%i"
    set "TCL_ROOT=!PYTHON_PREFIX!\tcl"
    if not exist "!TCL_ROOT!\tcl8.6\init.tcl" if not exist "!TCL_ROOT!\init.tcl" (
        echo [WARN] Tcl library not found at standard path !TCL_ROOT!, relying on Nuitka tk-inter plugin auto-detection...
    )
    rem Compress the outer onefile launcher so it does not retain a second
    rem full, uncompressed runtime on disk. The shared cache still lets the
    rem GUI, daemon, and watchdog reuse one extracted runtime.
    set "STYLE_FLAGS=--onefile --enable-plugin=tk-inter --onefile-tempdir-spec={CACHE_DIR}/ZeroWatch/extracted"
) else (
    set "STYLE_FLAGS=--standalone --enable-plugin=tk-inter"
)

call :run_compile
set "BUILD_EXIT=%ERRORLEVEL%"
if not "%BUILD_EXIT%"=="0" (
    echo [WARN] Zig build failed with exit code %BUILD_EXIT%. Retrying without --zig...
    if "%CLEAN_BUILD%"=="1" (
        if exist "build\sentinel_agent.build" rd /s /q "build\sentinel_agent.build"
        if exist "build\sentinel_agent.onefile-build" rd /s /q "build\sentinel_agent.onefile-build"
    )
    set "BASE_FLAGS=--assume-yes-for-downloads --windows-console-mode=disable --output-dir=build --output-filename=%OUTPUT_NAME% %ICON_FLAG% --include-data-file=%ICON_PATH%=favicon.ico %PACKAGE_FLAGS% %DATA_FLAGS% %SPEED_FLAGS%"
    call :run_compile
    set "BUILD_EXIT=%ERRORLEVEL%"
)

del /q "%BUILD_CFG%" >nul 2>nul
if not "%BUILD_EXIT%"=="0" (
    set "LAST_ERROR_MSG=Build failed after retry."
    goto build_failed
)

goto build_success

:run_compile
if /I "%BUILD_MODE%"=="admin" (
    py -3.11 -m nuitka ^
            %BASE_FLAGS% ^
            %STYLE_FLAGS% ^
            --company-name="DeepCytes" ^
            --product-name="ZeroWatch Sentinel Agent" ^
            --file-description="ZeroWatch Endpoint Security Agent" ^
            --file-version=1.1.1.0 ^
            --product-version=1.1.1.0 ^
            --windows-uac-admin ^
            sentinel_agent.py
) else (
    py -3.11 -m nuitka ^
            %BASE_FLAGS% ^
            %STYLE_FLAGS% ^
            --company-name="DeepCytes" ^
            --product-name="ZeroWatch Sentinel Agent" ^
            --file-description="ZeroWatch Endpoint Security Agent" ^
            --file-version=1.1.1.0 ^
            --product-version=1.1.1.0 ^
            sentinel_agent.py
)
exit /b %ERRORLEVEL%

:build_success

if /I "%BUILD_STYLE%"=="standalone" if not exist "build\sentinel_agent.dist\%OUTPUT_NAME%" (
    set "LAST_ERROR_MSG=Build completed without producing build\sentinel_agent.dist\%OUTPUT_NAME%."
    goto build_failed
)

if /I "%BUILD_STYLE%"=="onefile" if not exist "build\%OUTPUT_NAME%" (
    set "LAST_ERROR_MSG=Build completed without producing build\%OUTPUT_NAME%."
    goto build_failed
)

echo.
echo [5/5] Build complete!
if /I "%BUILD_STYLE%"=="onefile" (
    echo       Output: build\%OUTPUT_NAME%
) else (
    echo       Output: build\sentinel_agent.dist\%OUTPUT_NAME%
)
echo.

echo [CLEANUP] Cleaning temporary build artifacts...
rem Retain compilation cache for fast incremental rebuilds unless /clean was specified
if "%CLEAN_BUILD%"=="1" (
    if exist "build\sentinel_agent.build" rd /s /q "build\sentinel_agent.build"
    if exist "build\sentinel_agent.onefile-build" rd /s /q "build\sentinel_agent.onefile-build"
)
if /I "%BUILD_STYLE%"=="onefile" if exist "build\sentinel_agent.dist" rd /s /q "build\sentinel_agent.dist" >nul 2>nul
if exist "__pycache__" rd /s /q "__pycache__"
echo       Artifacts cleaned.
echo.
echo [NOTE] This EXE is pinned to: %BASE_API_URL%
echo [NOTE] If Microsoft Defender blocks it, sign the binary with a trusted code-signing certificate.
echo.
exit /b 0

:build_failed
if exist "%BUILD_CFG%" del /q "%BUILD_CFG%" >nul 2>nul
if not defined BUILD_EXIT set "BUILD_EXIT=1"
echo [ERROR] %LAST_ERROR_MSG%
echo [ERROR] Exit code: %BUILD_EXIT%
echo.
echo Build did not finish. Review the error messages above.
pause
exit /b %BUILD_EXIT%

