@echo off
setlocal EnableExtensions EnableDelayedExpansion
cd /d "%~dp0"

echo ============================================
echo  SentinelAgent Build Pipeline (PyInstaller Encryption)
echo ============================================
echo.

set "BUILD_MODE=user"
set "OUTPUT_NAME=SentinelAgent"
set "BUILD_STYLE=onefile"
set "SERVER_PRESET="
set "CUSTOM_SERVER_URL="
set "LAST_ERROR_MSG="
set "ICON_PATH=%~dp0resources\favicon.ico"
set "ICON_FLAG="
set "CONSOLE_FLAG=--noconsole"
set "ENCRYPTION_KEY=D33pCytes2026S3c"

if exist "%ICON_PATH%" (
    set "ICON_FLAG=--icon=%ICON_PATH%"
)

:parse_args
if "%~1"=="" goto args_done
if /I "%~1"=="/admin" (
    set "BUILD_MODE=admin"
    shift
    goto parse_args
)
if /I "%~1"=="/console" (
    set "CONSOLE_FLAG="
    shift
    goto parse_args
)
if /I "%~1"=="/onefile" (
    set "BUILD_STYLE=onefile"
    shift
    goto parse_args
)
if /I "%~1"=="/standalone" (
    set "BUILD_STYLE=standalone"
    shift
    goto parse_args
)
if /I "%~1"=="/prod" (
    set "SERVER_PRESET=prod"
    shift
    goto parse_args
)
if /I "%~1"=="/demo" (
    set "SERVER_PRESET=demo"
    shift
    goto parse_args
)
if /I "%~1"=="/dev" (
    set "SERVER_PRESET=dev"
    shift
    goto parse_args
)
if /I "%~1"=="/server" (
    if "%~2"=="" (
        echo [ERROR] /server requires a URL argument.
        exit /b 1
    )
    set "SERVER_PRESET=custom"
    set "CUSTOM_SERVER_URL=%~2"
    shift
    shift
    goto parse_args
)

if "%~1" NEQ "" set "OUTPUT_NAME=%~1"
shift
goto parse_args

:args_done

if /I "%OUTPUT_NAME:~-4%"==".exe" (
    set "OUTPUT_NAME=%OUTPUT_NAME:~0,-4%"
)

if /I "%BUILD_MODE%"=="admin" (
    echo [Mode] Admin build enabled (UAC prompt required at launch)
) else (
    echo [Mode] User build (no forced UAC prompt)
)
if /I "%BUILD_STYLE%"=="onefile" (
    echo [Profile] Onefile - single EXE deliverable
) else (
    echo [Profile] Standalone - folder output
)
echo.

if not defined SERVER_PRESET (
    echo Select target server for this EXE:
    echo   [1] Production  - https://zerowatch.deepcytes.io
    echo   [2] Demo/Test   - https://zerowatch-testing.eastasia.cloudapp.azure.com
    echo   [3] Development - http://localhost:3001
    echo.
    choice /c 123 /n /m "Enter choice (1/2/3): "
    if errorlevel 3 (
        set "SERVER_PRESET=dev"
    ) else if errorlevel 2 (
        set "SERVER_PRESET=demo"
    ) else if errorlevel 1 (
        set "SERVER_PRESET=prod"
    )

    if not defined SERVER_PRESET (
        echo [ERROR] Failed to read server choice.
        echo [HINT] Use a preset flag like /prod, /demo, or /dev.
        exit /b 1
    )
)
echo [DEBUG] SERVER_PRESET resolved to: %SERVER_PRESET%

if /I "%SERVER_PRESET%"=="prod" set "RAW_SERVER_URL=https://zerowatch.deepcytes.io"
if /I "%SERVER_PRESET%"=="demo" set "RAW_SERVER_URL=https://zerowatch-testing.eastasia.cloudapp.azure.com"
if /I "%SERVER_PRESET%"=="dev" set "RAW_SERVER_URL=http://localhost:3001"
if /I "%SERVER_PRESET%"=="custom" set "RAW_SERVER_URL=%CUSTOM_SERVER_URL%"

if not defined RAW_SERVER_URL (
    echo [ERROR] Failed to resolve server URL.
    exit /b 1
)

set "BASE_API_URL=%RAW_SERVER_URL%"
if /I not "%BASE_API_URL:~-4%"=="/api" set "BASE_API_URL=%BASE_API_URL%/api"

echo [Server] EXE will be pinned to: %BASE_API_URL%
echo.

echo [1/4] Installing build dependencies (PyInstaller 5.x + tinyaes)...
rem We install pyinstaller<6.0 because version 6.0 removed the --key option
py -3.11 -m pip install "pyinstaller<6.0" tinyaes "setuptools<70.0.0" wmi requests zstandard "python-socketio[client]"
if errorlevel 1 (
    set "LAST_ERROR_MSG=Failed to install build dependencies."
    goto build_failed
)
echo.

echo [2/4] Writing build-time server config...
set "BUILD_CFG=agent_build_config.py"
> "%BUILD_CFG%" echo # Auto-generated by build_agent_pyinstaller_enc.bat
>> "%BUILD_CFG%" echo FORCED_BASE_API_URL = "%BASE_API_URL%"
if errorlevel 1 (
    set "LAST_ERROR_MSG=Failed to write %BUILD_CFG%."
    goto build_failed
)
echo.

echo [2.5/4] Validating certificate pinning configuration...
py -3.11 verify_pins.py %SERVER_PRESET%
if errorlevel 1 (
    echo [ERROR] Pin validation failed! Check error messages above.
    set "LAST_ERROR_MSG=Pin validation check failed."
    del /q "%BUILD_CFG%" >nul 2>nul
    goto build_failed
)
echo.

echo [3/4] Preparing output directory...
if not exist "build" mkdir "build"
if exist "build\dist\%OUTPUT_NAME%.exe" (
    del /f /q "build\dist\%OUTPUT_NAME%.exe" >nul 2>nul
    if exist "build\dist\%OUTPUT_NAME%.exe" (
        set "LAST_ERROR_MSG=build\dist\%OUTPUT_NAME%.exe is in use. Close SentinelAgent and retry."
        del /q "%BUILD_CFG%" >nul 2>nul
        goto build_failed
    )
)

echo.
echo [4/4] Packaging and encrypting with PyInstaller...
set "UAC_FLAG="
if /I "%BUILD_MODE%"=="admin" set "UAC_FLAG=--uac-admin"

set "STYLE_FLAGS="
if /I "%BUILD_STYLE%"=="onefile" (
    set "STYLE_FLAGS=--onefile"
) else (
    set "STYLE_FLAGS=--onedir"
)

rem Compiling with AES encryption key (requires PyInstaller 5.x)
py -3.11 -m PyInstaller --noconfirm %STYLE_FLAGS% %CONSOLE_FLAG% %UAC_FLAG% ^
    --name "%OUTPUT_NAME%" ^
    %ICON_FLAG% ^
    --add-data "%ICON_PATH%;." ^
    --key="%ENCRYPTION_KEY%" ^
    --distpath build\dist ^
    --workpath build\build ^
    --specpath build ^
    --hidden-import "tkinter" ^
    --hidden-import "wmi" ^
    --hidden-import "requests" ^
    --hidden-import "zstandard" ^
    --hidden-import "socketio" ^
    sentinel_agent.py

if errorlevel 1 (
    set "LAST_ERROR_MSG=PyInstaller build failed."
    goto build_failed
)

del /q "%BUILD_CFG%" >nul 2>nul

echo.
echo [DONE] Build complete!
if /I "%BUILD_STYLE%"=="onefile" (
    echo       Output: build\dist\%OUTPUT_NAME%.exe
) else (
    echo       Output: build\dist\%OUTPUT_NAME%\%OUTPUT_NAME%.exe
)
echo.
echo [CLEANUP] Removing build artifacts...
if exist "build\build" rd /s /q "build\build"
if exist "build\%OUTPUT_NAME%.spec" del /q "build\%OUTPUT_NAME%.spec"
echo       Artifacts cleaned.
echo.
echo [NOTE] This EXE is pinned to: %BASE_API_URL%
exit /b 0

:build_failed
if exist "%BUILD_CFG%" del /q "%BUILD_CFG%" >nul 2>nul
echo [ERROR] %LAST_ERROR_MSG%
echo.
pause
exit /b 1
